prompts:
  choice_prompt_1: Παρακαλώ πες μου τι είδους άρθρο είναι αυτο που γραφω κατω, από τις επιλογες Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μόνο με μία λεξη, από τα είδη που ανεφερα.
  choice_prompt_2: Πες μου τι είδους άρθρο είναι αυτο, από τις επιλογες Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μόνο με μία λεξη, από τα είδη που ανεφερα.
  choice_prompt_3: Πες μου τι είδους άρθρο είναι αυτο, από τις επιλογες Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μονολεκτικά, από τα είδη που ανεφερα.
  choice_prompt_4: Τι είδους άρθρο είναι αυτό; Μπορεί να είναι Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μόνο με μία λεξη, το είδος που αντιστοιχεί
  choice_prompt_5: Τι είδους άρθρο είναι αυτό; Μπορεί να είναι Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μόνο με το είδος που αντιστοιχεί.
  choice_prompt_6: Πες μου τι ειδους αρθρο είναι απο τις επιλογές Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε με μία λεξη.
  choice_prompt_7: Πες μου τι ειδους αρθρο είναι απο τις επιλογές Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Απάντησε μονολεκτικά.
  choice_prompt_8: Είναι αυτό το άρθρο κάποιο από αυτά τα είδη; Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή, Άλλο. Ποιο είδος είναι; Απάντησε με μια λεξη, το είδος του αρθου, ή όχι αν δεν υπάρχει αντιστοιχία.
  choice_prompt_9: Ποιο είδος θεωρείς είναι αυτό το άρθρο; Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή ή Άλλο; Απάντησε με μια λεξη, το είδος του αρθου.
  empty_prompt_1: Πες μου τι είδους άρθρο είναι αυτό. Απάντησε μονολεκτικά με το είδος του αρθρου.
  empty_prompt_2: Πες μου τι είδους άρθρο είναι αυτό. Απάντησε με μία λέξη με το είδος του αρθρου.
  precentage_choice_prompt_1: Ποίο από αυτά τα είδη είναι το άρθρο; Αρθρο, Επιστολή, Κριτική, Συνέντευξη, Συνταγή ή Άλλο; Απάντησε ποιο πιστεύεις ότι είναι και ποιό είναι το ποσοστό ακρίβειας της επιλογής σου.

models:
  llama_3_1_8b: llama3.1
  # llama_3_2_3b: llama3.2
  meltemi_instruct_7b: ilsp/meltemi-instruct
  meltemi_instruct_7b_v1_5: ilsp/meltemi-instruct-v1.5
  aya_8b: aya
  # mistral_7b: mistral
  # gemma2_7b: gemma2